### ISSUE TITLE
2.0: spawn refactor and docs - my suggestions

### ISSUE THREAD

**Issue by oskarkk** [Eredrim/pvparena#142]
I think that setting spawns is one of the most non-intuitive things in pvparena (as of 1.15.2) - many bad reviews are mentioning setting spawns, and people are asking about setting them all the time - so it's great that you're doing something with it. But looking at the doc in 2.0 branch, and testing the plugin build of that branch, I have some suggestions.

Here's a table from the 2.0 doc:

| Command                                                 | Definition                  |
|---------------------------------------------------------|-----------------------------|
| /pa [arena] spawn set (teamName) [spawnName] (class)    | Define a spawn for an arena |
| /pa [arena] spawn remove (teamName) [spawnName] (class) | Remove a spawn for an arena |

And some examples:
- `/pa ctf spawn set red spawn` - sets the red team's spawn of the arena "ctf"
- `/pa ctf spawn remove red spawn2` - removes the second red team's spawn of the arena "ctf"
- `/pa free spawn set spawnEAST` - sets "spawnEAST" of the arena "free"
- `/pa ctf spawn set red spawn Pyro` - sets spawn only for Pyro class of red team

# 1. Brackets

The first thing that's wrong with this is applicable to all commands in the docs. I'd say you're presenting the syntax of the commands wrongly - square brackets are usually used with things that are optional, not required. Also, normal parentheses are seldom used when presenting syntax of the commands - angle brackets (`<`, `>`) are used more. See docs of the other popular plugins:

- Essentials: https://essinfo.xeya.me/commands.html
- WorldGuard: https://worldguard.enginehub.org/en/latest/commands/
- Multiverse: https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference (here curly brackets are used for required args, but still square brackets for optional args)
- LuckPerms: https://luckperms.net/wiki/Command-Usage

And it's like that not only in Minecraft commands, but also in tools like git (see for example https://git-scm.com/docs/git-commit), or Linux shell tools like cp, ls etc. (https://man7.org/linux/man-pages/man1/cp.1.html).

So, I think that it would be much better if we used the syntax that is used in almost every other plugin doc, so the table above should look like:

| Command                                                 | Definition                  |
|---------------------------------------------------------|-----------------------------|
| /pa [arena] spawn set [teamName] \<spawnName> [class]    | Define a spawn for an arena |
| /pa [arena] spawn remove [teamName] \<spawnName> [class] | Remove a spawn for an arena |

If you agree with this, I can edit every doc page of pvp arena in both master and 2.0 branches to use this style.

# 2. Order of arguments

I think that in a command like this the required argument should come before optional arguments. It may also make the code for parsing these commands simpler. So, I would rather recommend `/pa [arena] spawn set <spawnName> [teamName] [class]`.

Think of tab completion. It would be better if after writing `/pa myArena spawn set` the plugin would propose you `spawn`, `lounge`, `exit`, `spectator`, not a mix of spawn types and teams like this:

![image](https://user-images.githubusercontent.com/16339637/163039959-ce9aa0be-3d39-4ec4-b034-f0270c2fdcda.png)

I think this mix is confusing.

# 3. Spawn types

I think that the spawn name being also the spawn type is a bad design. It's not intuitive. I'm proposing:

`/pa [arena] spawn set <spawnType> [teamName] [spawnName] [class]`

Spawn name would be optional for some types of spawns - `exit` and `spectator`, and also for lounge if the arena is FFA. Examples of commands with the syntax I'm proposing:
- `/pa ctf spawn set spawn red 1`
- `/pa ctf spawn remove spawn red 2`
- `/pa free spawn set spawn east`
- `/pa ctf spawn set spawn red 1 Pyro`
- `/pa free spawn exit`
- `/pa free spawn lounge`

It would really be easier for new users and more intuitive. I think that parsing of these commands would also be easier.

# 4. Change type "spawn" to something else, for example "fight"

Imagine you're just downloaded the plugin and you're using it for the first time. Look at this command: `/pa myArena spawn set spawn`. It's confusing. Why there's `spawn` two times? `spawn` is a type of spawn?

I'm proposing changing that to something like `fight`. It would be logical:
- `lounge` - the point where player would spawn before fighting
- `exit` - the point where player would spawn after fighting
- `spectator` - the point where player would spawn when spectating
- `fight` - the point where player would spawn when fighting

Looking at the command `/pa free spawn set fight` we can guess that we're setting the spawn that will be used for fighting.

# 5. Configuration

Also, I'm proposing a big change in how spawns are saved in the configuration files. Spawns in arena config in 2.0 right now look like:

```
spawns:
  red_spawn: world,105,72,-341,-80.45086669921875,11.999911308288574
  red_spawn2: world,105,72,-340,-62.626708984375,25.499597549438477
  blue_spawn: world,110,72,-341,-80.45086669921875,11.999911308288574
  blue_spawn2: world,103,72,-340,-89.74935913085938,10.649736404418945
  blue_lounge: world,103,72,-338,-62.626708984375,25.499597549438477
  red_lounge: world,103,72,-338,-62.626708984375,25.499597549438477
  exit: world,104,72,-340,-62.626708984375,25.499597549438477
  spectator: world,105,72,-340,-62.626708984375,25.499597549438477
```

I'm proposing something hierarchical, like:

```
spawns:
  fight:
    red:
      '1':
        location: world,105,72,-341,-80.45086669921875,11.999911308288574
      '2':
        location: world,105,72,-340,-62.626708984375,25.499597549438477
    blue:
      '1':
        location: world,105,72,-341,-80.45086669921875,11.999911308288574
      '2':
        location: world,105,72,-340,-62.626708984375,25.499597549438477
  lounge:
    red:
      location: world,103,72,-338,-62.626708984375,25.499597549438477
    blue:
      location: world,103,72,-338,-62.626708984375,25.499597549438477
  exit:
    location: world,104,72,-340,-62.626708984375,25.499597549438477
  spectator:
    location: world,105,72,-340,-62.626708984375,25.499597549438477
```

With spawns for classes, it would look like:

```
spawns:
  fight:
    red:
      '1':
        location: world,105,72,-341,-80.45086669921875,11.999911308288574
        class: Pyro
      '2':
        location: world,105,72,-340,-62.626708984375,25.499597549438477
        class: Swordsman
    blue:
      '1':
        location: world,105,72,-341,-80.45086669921875,11.999911308288574
        class: Pyro
      '2':
        location: world,105,72,-340,-62.626708984375,25.499597549438477
        class: Swordsman
```

It would be a major change, but I think it's the right direction, that will lead to cleaner code, simple logic, easier maintenance. The properties of spawn would actually be a separate properties in the configuration, they wouldn't be extracted from strings. Also, think about the future. With configuration like this, you could sometime add new properties to each spawn. A very simple example:

```
spawns:
  fight:
    '1':
      location: world,105,72,-341,-80.45086669921875,11.999911308288574
      class: Pyro
      greeting: Welcome to spawn point for pyros!
      healthModification: -2
    '2':
      location: world,105,72,-340,-62.626708984375,25.499597549438477
      class: Swordsman
      greeting: Welcome to spawn point for swordsmen!
      healthModification: 2
```

In this example when spawning in each spawn the player would get a different welcome message and would spawn with specified change in HP. Of course that's only an example what could be done with configuration like that - it could be used by some new modules or something.

# 6. Alternatives: maybe spawns with unique names? Separate subcommands for setting the class, team, offset?

It's an alternative for what I described above in points 2, 3 and 5. Maybe it would be better if spawns had unique names within each type, then the configuration could look like:

```
spawns:
  fight:
    '1':
      location: world,105,72,-341,-80.45086669921875,11.999911308288574
      class: Pyro
      team: red
    '2':
      location: world,105,72,-340,-62.626708984375,25.499597549438477
      class: Swordsman
      team: red
    '3':
      location: world,105,72,-341,-80.45086669921875,11.999911308288574
      class: Pyro
      team: blue
    '4':
      location: world,105,72,-340,-62.626708984375,25.499597549438477
      class: Swordsman
      team: blue
  lounge:
    '1':
      location: world,103,72,-338,-62.626708984375,25.499597549438477
      team: red
    '2':
      location: world,103,72,-338,-62.626708984375,25.499597549438477
      team: blue
```

Then you could change the team of an existing spawn with a new subcommand like:

`/pa [arena] spawn setteam <spawnType> <spawnName> <newTeam>`

And then you could also set class with a separate subcommand:

`/pa [arena] spawn setclass <spawnType> <spawnName> <newClass>`

Then it would be easy to edit spawns of an arena - change the team of some spawn without setting and deleting, etc. Also, there's this in the doc:

`/pa [arena] spawn [spawnname] offset X Y Z`

I'm not sure if it's implemented yet, but it would go nicely with my proposals above, in the form:

`/pa [arena] spawn offset <spawnType> <spawnName> <X> <Y> <Z>`

And the config could look like:

```
spawns:
  fight:
    '1':
      location: world,105,72,-341,-80.45086669921875,11.999911308288574
      class: Pyro
      offset: 0,0.5,0
    '2':
      location: world,105,72,-340,-62.626708984375,25.499597549438477
      class: Swordsman
      offset: 0,0.5,0
```

Or maybe we could just have unique names for all spawns of the arena, which would be similar to what we have now, but the type still wouldn't be a part of the name. Config could look like:

```
spawns:
  '1':
    location: world,105,72,-341,-80.45086669921875,11.999911308288574
    team: red
    type: fight
  '2':
    location: world,105,72,-340,-62.626708984375,25.499597549438477
    team: blue
    type: fight
  '3':
    location: world,105,72,-341,-80.45086669921875,11.999911308288574
    team: red
    type: lounge
  '4':
    location: world,105,72,-340,-62.626708984375,25.499597549438477
    team: blue
    type: lounge
  '5':
    location: world,105,72,-340,-62.626708984375,25.499597549438477
    team: blue
    type: exit
```

Of course, user could have chosen any name for each of these spawns, it could be like:

```
spawns:
  'redteam':
    location: world,105,72,-341,-80.45086669921875,11.999911308288574
    team: red
    type: fight
  'blueteam':
    location: world,105,72,-340,-62.626708984375,25.499597549438477
    team: blue
    type: fight
```

... but the name of the spawn wouldn't be parsed as the type of the spawn. Theoretically you could have a spawn named "bluespawn" that would be a red team's spawn.

We could have commands like:

```
/pa [arena] spawn set <spawnName> [spawnType] [teamName]
/pa [arena] spawn setteam <spawnName> <teamName>
/pa [arena] spawn setclass <spawnName> <className>
/pa [arena] spawn settype <spawnName> <typeName>
/pa [arena] spawn remove <spawnName>
/pa [arena] spawn rename <oldName> <newName>
/pa [arena] spawn list [spawnType] [teamName]
```

Not sure if it would be better than just staying with what I described in points 3-5.

Pros:
 - it would be very versatile, you could easily do everything with each spawn with commands - change its type, team, rename it... (but with the solution from points 3-5 you could easily do the same thing by editing the config file)

Cons:
 - harder to understand for new users
 - it could be more chaotic (you would have to come up with an unique name for each spawn and could easily mix them up)

I would rather do this the way I described in points 3-5. Anyway, I would change the config files and separate the spawn types form spawn names.

# The end

Every one of these points is a separate suggestion, every one of them can be implemented without implementing others. I really think that setting spawns is the most important part of the configuration of this plugin, so it should be done right - it has big impact on whether the user will start to use it, or delete it and forget about it. I also think that error messages in 1.15.2 are very bad, they don't really help average user understand what's wrong and how the command should be used - I myself was very confused when I started using pvparena. I haven't checked if this was changed in 2.0 - if yes, good, if not, I'll probably propose how they could be changed.

I can help with some of these suggestions, especially with the first point about square braces in docs - I can do this right now if you're agree with me.

Maybe I'll write an example doc page for the spawn command that will help you understand my proposal, and I think it would show how much clearer the spawn configuration would be if my proposal was implemented.

Thanks for your attention.
