### ISSUE TITLE
Serialize custom potion effects

### ISSUE THREAD

**Issue by Eredrim** [Eredrim/pvparena#59]
Custom potion effects are not correctly serialized in configuration and can not be loaded. Here is an example:

```yaml

- type: SPLASH_POTION
meta:
display-name: Potion of Blindness
potion-type: minecraft:water
custom-effects:
- ==: PotionEffect
effect: 15
duration: 300
amplifier: 0
ambient: false
has-particles: true
has-icon: true
- ==: PotionEffect
effect: 24
duration: 300
amplifier: 0
ambient: false
has-particles: true
has-icon: true
```
